package ie.gmit.sw.graph;

/**
 * 
 * @author g00196984 - Andrej Lavrinovic
 * 
 * Class Edge represents connection between nodes for digraph where
 * connection is directional.
 * It contains Start node and end node
 *
 */
public class Edge {

	private Node start;
	private Node end;
	
	/*
	 * Constructors
	 * Generated by Eclipse
	 */
	public Edge() {}

	public Edge(Node start){
		this.start = start;
	}

	public Edge(Node start, Node end) {
		this();
		this.end = end;
	}

	/*
	 *  getters/setters
	 *  Generated by Eclipse
	 */
	public Node getStart() {
		return start;
	}

	public void setStart(Node start) {
		this.start = start;
	}

	public Node getEnd() {
		return end;
	}

	public void setEnd(Node end) {
		this.end = end;
	}
	
	
}
