package ie.gmit.sw.graph;

/**
 * 
 * 
 * Class Edge represents connection between nodes for digraph where
 * connection is directional.
 * It contains start node and end node.
 * 
 * @author g00196984 - Andrej Lavrinovic
 * 
 *
 */
public class Edge {

	private Node start;
	private Node end;
	
	/*
	 * Constructors
	 * Generated by Eclipse
	 */
	
	/**
	 * Default constructor.
	 */
	public Edge() {}

	/**
	 * Parameterized constructor.
	 * @param start represents outgoing node (current).
	 * @param end represents Node with type that depends on current (start) node.
	 */
	public Edge(Node start, Node end) {
		this.start = start;
		this.end = end;
	}

	/*
	 *  getters/setters
	 *  Generated by Eclipse
	 */
	
	/**
	 * 
	 * @return Returns start node.
	 */
	public Node getStart() {
		return start;
	}

	/**
	 * 
	 * @param start represents outgoing node (current).
	 */
	public void setStart(Node start) {
		this.start = start;
	}

	/**
	 * 
	 * @return Returns end node.
	 */
	public Node getEnd() {
		return end;
	}

	/**
	 * 
	 * @param end represents node that start Node (current) pointing to.
	 */
	public void setEnd(Node end) {
		this.end = end;
	}
	
	/**
	 * 
	 * @param start represents outgoing node (current).
	 * @param end represents node that start Node (current) pointing to.
	 */
	public void setEdge(Node start, Node end){
		this.start = start;
		this.end = end;
	}
}
