package ie.gmit.sw.graph;

import java.util.LinkedList;
import java.util.List;

public class JarGraph {

	private List<Node> graph;
	
	// Constructors
	public JarGraph(){
		this.graph = new LinkedList<Node>();
	}
	
	public JarGraph(List<Node> n){
		this.graph = n;
	}

	/*
	 * Delegated methods generated by Eclipse
	 */
	public boolean containsNode(Node n) {
		return graph.contains(n);
	}

	public boolean addNode(Node n) {
		return graph.add(n);
	}

	public Node getNode(int index) {
		return graph.get(index);
	}

	public int nodesNumber() {
		return graph.size();
	}
}
