package ie.gmit.sw.graph;

import java.util.LinkedList;
import java.util.List;

public class JarGraph {

	private List<Node> graph = new LinkedList<Node>();

	/*
	 * Delegated methods generated by Eclipse
	 */
	public boolean containsNode(Node n) {
		return graph.contains(n);
	}

	public boolean addNode(Node n) {
		return graph.add(n);
	}

	public Node getNode(int index) {
		return graph.get(index);
	}

	public int graphSize() {
		return graph.size();
	}
}
