package ie.gmit.sw.measure;

import java.lang.reflect.AnnotatedType;

import ie.gmit.sw.reflection.ClassLab;
import ie.gmit.sw.reflection.JarContent;

public class EfferentCoupling {

	private JarContent deps;
	private int depNum;
	private Class cl;
	private JarContent cls;
	
	private ClassLab cLab = new ClassLab();
	
	// Constructor using fields -> generated by eclipse
	public EfferentCoupling(Class cl, JarContent cls) {
		this.cl = cl;
		this.cls = cls;
		checkDependencies();
	}
	
	/*
	 * Efferent Coupling is a number of types, interfaces
	 * and superclasses that given class is depends on.
	 * 
	 * checkDependenies method checks all dependencies for given class
	 */
	public void checkDependencies(){
		
		this.deps = new JarContent();
		
		// 1) implemented interfaces
		JarContent ifaces = cLab.getAnnotatedInterfaces(this.cl);
		if(ifaces.numberOfClasses() > 0){
			for(int i = 0; i < ifaces.numberOfClasses(); i ++){
				this.deps.addClass(ifaces.getClass(i));
			}
		}
		
		// 2) extended superclass
		Class superclass = cLab.getSuperclass(this.cl, this.cls);
		if(superclass != null){
			this.deps.addClass(superclass);
		}
		
		// 3) Declared instancies
		JarContent instances = cLab.getInstances(this.cls, this.cl);
		addDeps(instances);
		
		// 4) Constructors -> params
		JarContent constParams = cLab.getConstructorParameters(this.cls, this.cl);
		addDeps(constParams);
		
		// 5) Methods -> params
		JarContent methodParams = cLab.getConstructorParameters(this.cls, this.cl);
		addDeps(methodParams);
		
		// 6) Methods Return type
		JarContent returnType = cLab.getMethodReturnType(this.cls, this.cl);
		addDeps(returnType);
	}
	
	private void addDeps(JarContent d){
		if(d.numberOfClasses() > 0){
			for(int i = 0; i < d.numberOfClasses(); i++){
				if(!cLab.typeFilter(this.deps, d.getClass(i))){
					this.deps.addClass(d.getClass(i));
				}
			}
		}
	}

	public JarContent getDeps() {
		return deps;
	}

	public int getDepNum() {
		return deps.numberOfClasses();
	}
}
